// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_Mew2qUuegnBJ-CSVCnn7Q1FkOjPbek',
    appId: '1:609762591225:web:da9118646e3f1e6b973d28',
    messagingSenderId: '609762591225',
    projectId: 'datemadly',
    authDomain: 'datemadly.firebaseapp.com',
    storageBucket: 'datemadly.appspot.com',
    measurementId: 'G-Z7147GY8FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1fpJigaP_vMcmaQo1pWdazJ__CI40oM',
    appId: '1:609762591225:android:a758a005bccd0c75973d28',
    messagingSenderId: '609762591225',
    projectId: 'datemadly',
    storageBucket: 'datemadly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBda3pBiWKvblel8QXYZFu1FD00N4jqsLg',
    appId: '1:609762591225:ios:6fa34cdf920b6ccb973d28',
    messagingSenderId: '609762591225',
    projectId: 'datemadly',
    storageBucket: 'datemadly.appspot.com',
    iosClientId:
        '609762591225-kfn581lrbauo20kr8ho0nl6g9g4dpkbe.apps.googleusercontent.com',
    iosBundleId: 'com.datemadly.date.findpartner.love.dateMadlyApp',
  );
}
